name: .NET Build and Test

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    name: Build and Test (matrix)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        configuration: [Release]
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore src/Badger.Data.sln

      - name: Build
        run: dotnet build src/Badger.Data.sln --configuration ${{ matrix.configuration }} --no-restore

      - name: Test
        run: dotnet test src/Badger.Data.sln --filter Category!=Integration --configuration ${{ matrix.configuration }} --no-build --logger "trx;LogFileName=TestResults/test-results.trx"

      - name: Test Report
        if: always()
        uses: dorny/test-reporter@v3
        with:
          name: dotnet tests
          path: '**/TestResults/*.trx'
          reporter: dotnet-trx
